# Generated by Django 3.1.2 on 2020-12-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('year_of_warranty', models.PositiveIntegerField(default=1)),
                ('finanace_plan', models.CharField(default='unavaible', max_length=20)),
            ],
        ),
    ]
