# Generated by Django 3.1.2 on 2020-12-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_car_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_plan',
            new_name='Carplan',
        ),
    ]
