# Generated by Django 3.1.2 on 2020-12-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_carspecs_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='car_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='nameFile'),
        ),
    ]
