# Generated by Django 3.1.2 on 2020-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20201212_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecs',
            name='car_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Images/'),
        ),
    ]
