# Generated by Django 3.1.2 on 2020-12-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20201212_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_plan',
        ),
        migrations.DeleteModel(
            name='Carplan',
        ),
    ]
