# Generated by Django 3.1.2 on 2021-01-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20201212_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('year_of_warranty', models.PositiveIntegerField(default=1)),
                ('finanace_plan', models.CharField(default='unavaible', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carspecs',
            name='car_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.carplan'),
        ),
    ]
